FROM nginx:alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/quikooo.conf
RUN rm -f /etc/nginx/conf.d/default.conf
COPY apps/customer-web/dist /usr/share/nginx/html/customer
COPY apps/merchant-studio/dist /usr/share/nginx/html/merchant
COPY apps/driver-fleet/dist /usr/share/nginx/html/driver
COPY apps/agent-app/dist /usr/share/nginx/html/agent
COPY apps/admin-console/dist /usr/share/nginx/html/admin
EXPOSE 80
